apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: clintloseedev-us-tls
spec:
  secretName: clintloseedev-us-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: clintloseedev.us
  dnsNames:
    - clintloseedev.us
    - www.clintloseedev.us
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - clintloseedev.us
          - www.clintloseedev.us
